pipeline { 
    agent any  
    environment {
        def mvn = "/home/pi/apache-maven/bin/mvn"
        JAVA_HOME= "/usr/lib/jvm/jdk-17.0.1+12"
    }
    stages { 
        stage(' Compile') { 
            steps { 
            	dir("SciabaladaGourmet"){
					sh '${mvn} clean install'
 				}
            }
        }
        stage('Deploy to Tomcat'){
			steps{
            	dir("SciabaladaGourmet"){
	            	sh '${mvn} tomcat7:redeploy -Dhostname=ftvlogger -Dport=8080 -DserverName=ftvTomcatServer'   
	            } 
			}
        }
    }
}